package br.com.w2c.model.enums;

/**
 * 
 * @author charlles
 * @since 20/10/2013
 */
public enum ParametroGeral {
	
	ANO_LETIVO("ANO_LETIVO"),            
	SMTP_EMAIL_SERVIDOR("MAIL_SMTP_SERVER"),          
	EMAIL_REMETENTE("MAIL_SENDER"),          
	SENHA_EMAIL_REMETENTE("MAIL_PASSWORD"),      
	NOME_REMETENTE("MAIL_NAME_SENDER"),
	EMAIL_CONTATO_ADM("EMAIL_CONTATO_ADM"),
	NOME_EMPRESA("NOME_EMPRESA"),
	STATUS_ATUALIZACAO_WEB("STATUS_ATUALIZACAO_WEB"),
	ULTIMA_ATUALIZACAO_WEB("ULTIMA_ATUALIZACAO_WEB"),
	VERSAO_BASE_DADOS("VERSAO_BASE_DADOS"),
	JOB_EMAIL_LIGADO("JOB_EMAIL_LIGADO"),
	JOB_SINCRONIZACAO_LIGADO("JOB_SINCRONIZACAO_LIGADO"),
	JOB_SINCRONIZACAO_TEMPO("JOB_SINCRONIZACAO_TEMPO"),
	JOB_SMS_EMAIL_TEMPO("JOB_SMS_EMAIL_TEMPO"),
	JOB_SMS_LIGADO("JOB_SMS_LIGADO");


	private String chave;
	
	ParametroGeral(String chave) {
		this.chave = chave;
	}
	
	public String getChave() {
		return chave;
	}
}